//movies
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS'
export const SAVE_MOVIES_SUCCESS = 'SAVE_MOVIES_SUCCESS'
export const UPDATE_MOVIES_SUCCESS = 'UPDATE_MOVIES_SUCCESS'
